#!/bin/bash

# Viet Hoang
# July 23, 2019

#################################################################################

# This script transforms an atlas into subject (DWI) space. For this script to 
# function, a T1w image of the subject in DWI space must be provided. This script
# registers MNI 152 (image space of atlas) to the T1w image. 

# The T1w image (in DWI space), MNI 152 brain and the atlas (in MNI 152 space) 
# are required. We outline the steps for registration:
#   1. Perform non-linear registration on MNI 152 using T1w image as a reference
#      to produce the matrix MNI_2_T1w
#   2. Apply matrix MNI_2_T1w to the atlas to transform it to subject space.

# Example usage:
# Atlas_2_DWI -a PATH/to/atlas -b PATH/to/MNI_152 -r PATH/to/T1w \
# -o PATH/to/output/atlas

################################################################################

while getopts "a:b:r:o:" flag; do 
    case ${flag} in
        a) file_atlas=${OPTARG};;
        b) file_MNI=${OPTARG};;
        r) file_t1w=${OPTARG};;
        o) file_out=${OPTARG};;
    esac
done

parent="$(dirname "$file_t1w")"
mkdir -p $parent/Atlas_Registration_tmp
output_dir=$parent/Atlas_Registration_tmp

# flirt -dof 12 -cost mutualinfo \
# -in $file_MNI -ref $file_t1w \
# -omat $output_dir/MNI_152_2_T1w_lin.mat \
# -out $output_dir/MNI_152_lin.nii.gz

# 1. Perform non-linear registration on MNI 152 using T1w image as a reference
# to produce the matrix MNI_2_T1w
fnirt --in=$file_MNI --ref=$file_t1w --aff=$output_dir/MNI_152_2_T1w_lin.mat --cout=$output_dir/MNI_152_2_T1w_warp.nii.gz --config=$output_dir/CLMS-LONDON-3_002-LON-3_stu_019_m00_TEST_0_config.cnf
applywarp --ref=$file_t1w --in=$file_MNI --warp=$output_dir/MNI_152_2_T1w_warp.nii.gz --out=$output_dir/MNI_152_2_T1w_warp_final.nii.gz
# fnirt --ref=$file_t1w --in=$file_MNI --cout=$output_dir/MNI1_152_warp.nii.gz --out=$file_out
 
# # 2. Apply matrix MNI_2_T1w to the atlas to transform it to subject space.
# applywarp --ref=example_func --in=mask_in_standard_space --warp=highres2standard_warp_inv --postmat=highres2example_func.mat --out=mask_in_functional_space
# 