#!/usr/bin/env bash

# Viet Hoang
# October 1, 2019

#################################################################################
# This script performs brain extraction on a diffusion weighted image. It uses
# various FSL tools and it outputs the following files:
# b=0 images (original volume, brain extracted volume, birnary brain mask)
# DWI image (brain extracted)

# Usage:
# dwi_bet <PATH/to/DWI> <fractional intensity threshold>

# Consult FSL documentation to learn more about fractional intensity threshold
#################################################################################

file_dwi=$1
frac_thresh=$2

parent="$(dirname "$file_dwi")"
name_dwi="$(basename ${file_dwi%.nii*})"

# Creates tmp folder for the outputs of fslsplit (it produces uneeded files)
mkdir $parent/tmp
cp $file_dwi $parent/tmp
cd $parent/tmp
# Splits all the volumes of a DWI into different files
fslsplit $name_dwi 
cd ~
# Moves the first volume (b=0 image) into the main directory
mv $parent/tmp/vol0000.nii.gz $parent/${name_dwi}_b0.nii.gz

# Calls BET for brain extraction on the b=0 image
# Outputs: brain extracted b=0 image and binary brain mask
bet $parent/${name_dwi}_b0.nii.gz \
$parent/${name_dwi}_b0_noskull \
-R -m -f $frac_thresh

# Apply brain mask to the original DWI
fslmaths $file_dwi \
-mas $parent/${name_dwi}_b0_noskull_mask.nii.gz \
$parent/${name_dwi}_noskull.nii.gz

rm -r $parent/tmp





