#!/usr/bin/env bash

# Viet Hoang
# July 15, 2019


#################################################################################

# This script registers a T1-weighted image to a diffusion weighted image WHILE 
# preserving the resolution of the T1w image.

# b=0 DWI and the T1w image are required. We outline the steps for registration:
#   1. Register DWI_b0 to T1w using FLIRT; we obtain the matrix DWI_b0_reg_2_T1w
#   2. Convert DWI_b0_reg_2_T1w matrix to MRtrix format
#   3. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_reg_2_DWI

# Example usage:
# t1w_2_dwi -i PATH/to/T1w -r PATH/to/DWI_b0 

################################################################################


# Reads the arguments that are passed into the script and creates an output dir.
# We use the built-in getops function and assign the path of the file to the 
# appropriate variable based on the flag. -r is the flag for the DWI_b0 
# (reference), -i is for T1w (input).

while getopts "i:r:o:" flag; do 
    case ${flag} in
        i) file_t1w=${OPTARG};;
        o) file_t1w_orig=${OPTARG};;
        r) file_b0=${OPTARG};;
    esac
done

parent="$(dirname "$file_t1w")"
t1w_name="$(basename ${file_t1w%.nii*})"
t1w_orig_name="$(basename ${file_t1w_orig%.nii*})"
mkdir -p $parent/${t1w_name}_T1w_2_DWI_tmp
tmp_dir=$parent/${t1w_name}_T1w_2_DWI_tmp


# 1. Register DWI_b0 to T1w using FLIRT; we obtain the matrix DWI_b0_reg_2_T1w 
flirt -dof 6 -cost mutualinfo \
-in $file_b0 -ref $file_t1w \
-omat $tmp_dir/DWI_b0_reg_2_T1w_tmp.mat

# 2. Convert DWI_b0_reg_2_T1w matrix to MRtrix format
transformconvert -quiet \
$tmp_dir/DWI_b0_reg_2_T1w_tmp.mat $file_b0 $file_t1w flirt_import \
$tmp_dir/DWI_b0_reg_2_T1w_tmp.txt

# 3. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_DTIsp
mrtransform $file_t1w \
-inverse -linear $tmp_dir/DWI_b0_reg_2_T1w_tmp.txt \
$parent/${t1w_name}_DTIsp.nii.gz

# 4. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_orig_DTIsp
mrtransform $file_t1w_orig \
-inverse -linear $tmp_dir/DWI_b0_reg_2_T1w_tmp.txt \
$parent/${t1w_orig_name}_DTIsp.nii.gz

# Remove tmp folder
rm -r $tmp_dir