#!/bin/bash

# Viet Hoang
# July 15, 2019


#################################################################################

# This script registers T1-weighted image to diffusion weighted image WHILE 
# preserving the resolution of the T1w image.

# b=0 DWI and the T1w image are required. We outline the steps for registration:
#   1. Register DWI_b0 to T1w using FLIRT; we obtain the matrix DWI_b0_reg_2_T1w
#   2. Convert DWI_b0_reg_2_T1w matrix to MRtrix format
#   3. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_reg_2_DWI

# Example usage:
# T1w_reg_2_DWI -i PATH/to/T1w -r PATH/to/DWI_b0 -o PATH/to/output/image

################################################################################


# Reads the arguments that are passed into the script and creates an output dir.
# We use the built-in getops function and assign the path of the file to the 
# appropriate variable based on the flag. -r is the flag for the DWI_b0 
# (reference), -i is for T1w (input) and -o is for the output image.

while getopts "i:r:o:" flag; do 
    case ${flag} in
        i) file_t1w=${OPTARG};;
        r) file_b0=${OPTARG};;
        o) file_out=${OPTARG};;
    esac
done

parent="$(dirname "$file_t1w")"
mkdir -p $parent/T1w_Registration_tmp
output_dir=$parent/T1w_Registration_tmp


# 1. Register DWI_b0 to T1w using FLIRT; we obtain the matrix DWI_b0_reg_2_T1w 
flirt -dof 6 -cost mutualinfo \
-in $file_b0 -ref $file_t1w \
-omat $output_dir/DWI_b0_reg_2_T1w_tmp.mat

# 2. Convert DWI_b0_reg_2_T1w matrix to MRtrix format
transformconvert -quiet \
$output_dir/DWI_b0_reg_2_T1w_tmp.mat $file_b0 $file_t1w flirt_import \
$output_dir/DWI_b0_reg_2_T1w_tmp.txt

# 3. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_reg_2_DWI
mrtransform $file_t1w -inverse -linear $output_dir/DWI_b0_reg_2_T1w_tmp.txt \
$file_out
