#!/usr/bin/env bash

# Viet Hoang
# December 29, 2019

###############################################################################
# This script creates inclusion ROI for various brain regions that can be used
# for tractography.
# ROIs extracted:
#   1. Corticospinal tract: Brain stem, precentral gyrus
#   2. Cingulum: Isthmus cingulate, Rostral anterior cingulate
#   3. Anterior thalamic radiation: Rostral middle frontal, thalamus
#   4. Superior longitudinal fasciculus: Supra marginal gyrus, caudal middle 
#      frontal 
# 
# Usage:
# aparc+aseg_2_roi PATH/to/aparc+aseg.nii.gz
###############################################################################

file_aparc=$1
parent="$(dirname "$file_aparc")"
name_aparc="$(basename ${file_aparc%.nii*})"

# Creates an output folder
mkdir $parent/roi

# Corticospinal tract:
# Brain stem
fslmaths $file_aparc \
-thr 16 -uthr 16 -bin \
$parent/roi/aparc+aseg_16_brainstem.nii.gz
# Precentral gyrus (LH)
fslmaths $file_aparc \
-thr 1024 -uthr 1024 -bin \
$parent/roi/aparc+aseg_1024_lh_precentral.nii.gz
# Precentral gyrus (RH)
fslmaths $file_aparc \
-thr 2024 -uthr 2024 -bin \
$parent/roi/aparc+aseg_2024_rh_precentral.nii.gz

# Cingulum:
# Isthmus cingulate (LH)
fslmaths $file_aparc \
-thr 1010 -uthr 1010 -bin \
$parent/roi/aparc+aseg_1010_lh_isthmuscingulate.nii.gz
# Isthmus cingulate (RH)
fslmaths $file_aparc \
-thr 2010 -uthr 2010 -bin \
$parent/roi/aparc+aseg_2010_rh_isthmuscingulate.nii.gz
# Rostral anterior cingulate (LH)
fslmaths $file_aparc \
-thr 1026 -uthr 1026 -bin \
$parent/roi/aparc+aseg_1026_lh_rostralanteriorcingulate.nii.gz
# Rostral anterior cingulate (RH)
fslmaths $file_aparc \
-thr 2026 -uthr 2026 -bin \
$parent/roi/aparc+aseg_2026_rh_rostralanteriorcingulate.nii.gz

# Anterior thalamic radiation:
# Rostral middle frontal (LH)
fslmaths $file_aparc \
-thr 1027 -uthr 1027 -bin \
$parent/roi/aparc+aseg_1027_lh_rostralmiddlefrontal.nii.gz
# Rostral middle frontal (RH)
fslmaths $file_aparc \
-thr 2027 -uthr 2027 -bin \
$parent/roi/aparc+aseg_2027_rh_rostralmiddlefrontal.nii.gz
# Thalamus (Left)
fslmaths $file_aparc \
-thr 10 -uthr 10 -bin \
$parent/roi/aparc+aseg_10_left_thalamus.nii.gz
# Thalamus (Right)
fslmaths $file_aparc \
-thr 49 -uthr 49 -bin \
$parent/roi/aparc+aseg_49_right_thalamus.nii.gz

# Superior longitudinal fasciculus:
# Supra marginal gyrus (LH)
fslmaths $file_aparc \
-thr 1031 -uthr 1031 -bin \
$parent/roi/aparc+aseg_1031_lh_supramarginal.nii.gz
# Supra marginal gyrus (RH)
fslmaths $file_aparc \
-thr 2031 -uthr 2031 -bin \
$parent/roi/aparc+aseg_2031_rh_supramarginal.nii.gz
# Caudal middle frontal (LH)
fslmaths $file_aparc \
-thr 1003 -uthr 1003 -bin \
$parent/roi/aparc+aseg_1003_lh_caudalmiddlefrontal.nii.gz
# Caudal middle frontal (RH)
fslmaths $file_aparc \
-thr 2003 -uthr 2003 -bin \
$parent/roi/aparc+aseg_2003_rh_caudalmiddlefrontal.nii.gz


