#!/usr/bin/env bash

# Viet Hoang
# April 10, 2021

###############################################################################
# This script reconstructs the corticospinal tract using probabalistic
# tractography. For this script, MRtrix 3 was used.

# Usage
# trk_gen -n subject_name -d dwi_img -l bval_file -c bvec_file -b b0_img -r dir_roi
###############################################################################


# Reads the arguments that are passed into the script and creates an output dir.
# We use the built-in getops function and assign the path of the file to the 
# appropriate variable based on the flag. -d is the flag for the DWI, -t is 
# for the 5tt image, etc.
while getopts 'n:d:l:c:b:t:r:' flag; do 
    case "${flag}" in
        n) name="${OPTARG}";;
        d) file_dwi="${OPTARG}";;
        l) file_bval="${OPTARG}";;
        c) file_bvec="${OPTARG}";;
        b) file_b0="${OPTARG}";;
        r) dir_roi="${OPTARG}";;      
    esac
done

parent="$(dirname "$file_dwi")"
mkdir -p $parent/constrained_spherical_deconvolution_cst
dir_output=$parent/constrained_spherical_deconvolution_cst
mkdir -p $parent/seg/cst_tract
dir_tract=$parent/seg/cst_tract

# 1. Convert the DWI into an uncompressed format.
mrconvert -quiet -fslgrad $file_bvec $file_bval -datatype float32 -strides 0,0,0,1 \
$file_dwi $dir_output/DWI.mif

# 2. Estimate the multi-shell, multi-tissue response function
dwi2response dhollander $dir_output/DWI.mif \
$dir_output/RF_WM.txt $dir_output/RF_GM.txt $dir_output/RF_CSF.txt \
-voxels $dir_output/RF_voxels.mif -nthreads 8

# 3. Create an FOD image using multi-shell, multi-tissue constrained spherical 
# deconvolution (MSMT-CSD)
dwi2fod msmt_csd -mask $file_b0 \
$dir_output/DWI.mif \
$dir_output/RF_WM.txt $dir_output/WM_FODs.mif \
$dir_output/RF_GM.txt $dir_output/GM.mif \
$dir_output/RF_CSF.txt $dir_output/CSF.mif \
-nthreads 8

# 3a. View the FOD image
mrconvert $dir_output/WM_FODs.mif - -coord 3 0 | \
mrcat $dir_output/CSF.mif $dir_output/GM.mif - $dir_output/tissueRGB.mif -axis 3
# mrview $dir_output/tissueRGB.mif -odf.load_sh $dir_output/WM_FODs.mif

# Renconstruct the CST using MRtrx's tckgen. Both the left and right CST are
# constructed. Additionally, for each tract (i.e left and right CST), two
# tractograms are generated. One tractogram has the start point be the brainstem
# and the endpoint be the motor cortex. The other tractogram has the start point
# be the motor cortex and the endpoint be the brainstem. These two tractograms
# are merged into one.
mkdir $dir_tract/cst

tckgen $dir_output/WM_FODs.mif $dir_tract/cst/${name}_lh_cst_start_end.tck \
-crop_at_gmwmi -seed_image $dir_roi/aparc+aseg_1024_lh_precentral_DTIsp.nii.gz \
-include $dir_roi/aparc+aseg_16_brainstem_DTIsp.nii.gz \
-select 2.5k -cutoff 0.05 -quiet -stop -seed_unidirectional -nthreads 2 -angle 30 \
&\
tckgen $dir_output/WM_FODs.mif $dir_tract/cst/${name}_lh_cst_end_start.tck \
-crop_at_gmwmi -seed_image $dir_roi/aparc+aseg_16_brainstem_DTIsp.nii.gz \
-include $dir_roi/aparc+aseg_1024_lh_precentral_DTIsp.nii.gz \
-select 2.5k -cutoff 0.05 -stop -seed_unidirectional -nthreads 2 -angle 30 \
&\
tckgen $dir_output/WM_FODs.mif $dir_tract/cst/${name}_rh_cst_start_end.tck \
-crop_at_gmwmi -seed_image $dir_roi/aparc+aseg_2024_rh_precentral_DTIsp.nii.gz \
-include $dir_roi/aparc+aseg_16_brainstem_DTIsp.nii.gz \
-select 2.5k -cutoff 0.05 -quiet -stop -seed_unidirectional -nthreads 2 -angle 30 \
&\
tckgen $dir_output/WM_FODs.mif $dir_tract/cst/${name}_rh_cst_end_start.tck \
-crop_at_gmwmi -seed_image $dir_roi/aparc+aseg_16_brainstem_DTIsp.nii.gz \
-include $dir_roi/aparc+aseg_2024_rh_precentral_DTIsp.nii.gz \
-select 2.5k -cutoff 0.05 -quiet -stop -seed_unidirectional -nthreads 2 -angle 30 \
&\
wait

echo "Finished reconstructing CST"

# Merge the two left CST tractgrams
tckedit $dir_tract/cst/${name}_lh_cst_start_end.tck \
$dir_tract/cst/${name}_lh_cst_end_start.tck \
$dir_tract/cst/${name}_lh_cst.tck

# Merge the two right CST tractograms
tckedit $dir_tract/cst/${name}_rh_cst_start_end.tck \
$dir_tract/cst/${name}_rh_cst_end_start.tck \
$dir_tract/cst/${name}_rh_cst.tck